name: tagpr

on:
  push:
    branches:
    - main

jobs:
  tagpr:
    # TODO: tagprのPRがマージされたときは実行したくない
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_FOR_TAGPR }}

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Build plugin
      run: |
        npm install
        npm run build

    - name: Test plugin
      run: |
        npm run test

    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_FOR_TAGPR }}
